#include <stdio.h>

int main(){
    printf("\n");
    printf("===================================================================\n");
    printf("------------------------------AQUARIUS-----------------------------\n");
    printf("!   Pengertian Umum:                                              !\n");
    printf("!   Aquarius diwakili oleh seorang pembawa air, yang melambangkan !\n");
    printf("!   kebebasan, kreativitas, dan inovasi. Aquarius adalah tanda    !\n");
    printf("!   udara yang mencerminkan idealisme, keunikan, dan keterbukaan. !\n");
    printf("!                                                                 !\n");
    printf("!   Tanggal      : 20 Januari - 18 Februari.                      !\n");
    printf("!   Sifat        : Inovatif, humanis, eksentrik.                  !\n");
    printf("!   Kelebihan    : Kreatif, toleran.                              !\n");
    printf("!   Kekurangan   : Tidak terikat, eksentrik                       !\n");
    printf("!   Cocok dengan : Gemini, Libra.                                 !\n");
    printf("!   Tambahan     : Suka berpikir ke depan, suka membantu orang.   !\n");
    printf("===================================================================\n");
    printf("\n");

    printf("\n");
    printf("===================================================================\n");
    printf("-------------------------------PISCES------------------------------\n");
    printf("!   Pengertian Umum:                                              !\n");
    printf("!   Pisces diwakili oleh ikan, yang melambangkan imajinasi,       !\n");
    printf("!   kepekaan, dan spiritualitas. Pisces adalah tanda air yang     !\n");
    printf("!   menyoroti empati, kreativitas, dan kepekaan.                  !\n");
    printf("!                                                                 !\n");
    printf("!   Tanggal      : 19 Februari - 20 Maret.                        !\n");
    printf("!   Sifat        : Sensitif, intuitif, impian.                    !\n");
    printf("!   Kelebihan    : Empati, kreatif.                               !\n");
    printf("!   Kekurangan   : Mudah terpengaruh, mudah terombang-ambing.     !\n");
    printf("!   Cocok dengan : Cancer, Scorpio.                               !\n");
    printf("!   Tambahan     : Romantis, suka berdaya khayal.                 !\n");
    printf("===================================================================\n");
    printf("\n");

    printf("\n");
    printf("===================================================================\n");
    printf("-------------------------------ARIES-------------------------------\n");
    printf("!   Pengertian Umum:                                              !\n");
    printf("!   Simbol zodiak ini adalah domba jantan, yang melambangkan      !\n");
    printf("!   kepemimpinan, keberanian, dan energi. Aries adalah tanda api  !\n");
    printf("!   yang mewakili awal, keberanian, dan semangat baru.            !\n");
    printf("!                                                                 !\n");
    printf("!   Tanggal      : 21 Maret - 19 April.                           !\n");
    printf("!   Sifat        : Energik, berani, impulsif.                     !\n");
    printf("!   Kelebihan    : Penuh semangat, berani mengambil risiko.       !\n");
    printf("!   Kekurangan   : Tidak sabar, mudah marah.                      !\n");
    printf("!   Cocok dengan : Libra, Leo.                                    !\n");
    printf("!   Tambahan     : Pemimpin alami, suka tantangan.                !\n");
    printf("===================================================================\n");
    printf("\n");

    printf("\n");
    printf("===================================================================\n");
    printf("-------------------------------TAURUS------------------------------\n");
    printf("!   Pengertian Umum:                                              !\n");
    printf("!   Taurus adalah simbol sapi jantan, yg melambangkan kestabilan, !\n");
    printf("!   keteguhan, dan kenyamanan. Taurus adalah tanda bumi yang      !\n");
    printf("!   menggambarkan kepraktisan, kesabaran, dan keandalan.          !\n");
    printf("!                                                                 !\n");
    printf("!   Tanggal      : 20 April - 20 Mei.                             !\n");
    printf("!   Sifat        : Sabar, stabil, materialistis.                  !\n");
    printf("!   Kelebihan    : Keuletan, kepraktisan.                         !\n");
    printf("!   Kekurangan   : Kepala batu, keras kepala.                     !\n");
    printf("!   Cocok dengan : Virgo, Capricorn.                              !\n");
    printf("!   Tambahan     : Senang kenyamanan, stabil dalam hubungan.      !\n");
    printf("===================================================================\n");
    printf("\n");

    printf("\n");
    printf("===================================================================\n");
    printf("-------------------------------GEMINI------------------------------\n");
    printf("!   Pengertian Umum:                                              !\n");
    printf("!   Simbolnya adalah kembar, yang mewakili dualitas dan           !\n");
    printf("!   kecerdasan. Gemini adalah tanda udara yang menggambarkan      !\n");
    printf("!   komunikasi, fleksibilitas, dan keterbukaan.                   !\n");
    printf("!                                                                 !\n");
    printf("!   Tanggal      : 21 Mei - 20 Juni.                              !\n");
    printf("!   Sifat        : Fleksibel, sosial, cerdas.                     !\n");
    printf("!   Kelebihan    : Adaptable, cerdas.                             !\n");
    printf("!   Kekurangan   : Cepat bosan, tidak konsisten.                  !\n");
    printf("!   Cocok dengan : Sagitarius, Aquarius.                          !\n");
    printf("!   Tambahan     : Penuh keingintahuan, pandai bicara.            !\n");
    printf("===================================================================\n");
    printf("\n");

    printf("\n");
    printf("===================================================================\n");
    printf("-------------------------------CANCER------------------------------\n");
    printf("!   Pengertian Umum:                                              !\n");
    printf("!   Cancer diwakili oleh kepiting, yang melambangkan perlindungan !\n");
    printf("!   , emosi, dan kedalaman. Cancer adalah tanda air yang          !\n");
    printf("!   menyoroti kelembutan, kepekaan, dan perhatian.                !\n");
    printf("!                                                                 !\n");
    printf("!   Tanggal      : 21 Juni - 22 Juli.                             !\n");
    printf("!   Sifat        : Emosional, sensitif, protektif.                !\n");
    printf("!   Kelebihan    : Empati tinggi, perhatian.                      !\n");
    printf("!   Kekurangan   : Mudah terluka, mudah tersinggung.              !\n");
    printf("!   Cocok dengan : Scorpio, Pisces.                               !\n");
    printf("!   Tambahan     : Kuat dalam hubungan keluarga, artistik.        !\n");
    printf("===================================================================\n");
    printf("\n");

    printf("\n");
    printf("===================================================================\n");
    printf("---------------------------------LEO-------------------------------\n");
    printf("!   Pengertian Umum:                                              !\n");
    printf("!   Leo adalah singa, simbol kekuatan, kebanggaan, dan keberanian.!\n");
    printf("!   Leo adalah tanda api yang mencerminkan kepemimpinan,          !\n");
    printf("!   kreativitas, dan keteguhan.                                   !\n");
    printf("!                                                                 !\n");
    printf("!   Tanggal      : 23 Juli - 22 Agustus.                          !\n");
    printf("!   Sifat        : Percaya diri, bersemangat, dominan.            !\n");
    printf("!   Kelebihan    : Karisma, kepemimpinan.                         !\n");
    printf("!   Kekurangan   : Egomaniak, suka pamer.                         !\n");
    printf("!   Cocok dengan : Aries, Sagitarius.                             !\n");
    printf("!   Tambahan     : Suka jadi pusat perhatian, setia.              !\n");
    printf("===================================================================\n");
    printf("\n");

    printf("\n");
    printf("===================================================================\n");
    printf("--------------------------------VIRGO------------------------------\n");
    printf("!   Pengertian Umum:                                              !\n");
    printf("!   Virgo diwakili oleh seorang perawan, yang melambangkan        !\n");
    printf("!   kebersihan, ketelitian, dan analisis. Virgo adalah tanda bumi !\n");
    printf("!   yang menyoroti keteraturan, kerendahan hati, dan kepraktisan. !\n");
    printf("!                                                                 !\n");
    printf("!   Tanggal      : 23 Agustus - 22 September.                     !\n");
    printf("!   Sifat        : Analitis, perfeksionis, kritis.                !\n");
    printf("!   Kelebihan    : Rinci, praktis.                                !\n");
    printf("!   Kekurangan   : Terlalu kritis, khawatir berlebihan.           !\n");
    printf("!   Cocok dengan : Taurus, Capricorn.                             !\n");
    printf("!   Tambahan     : Peduli detail, suka membantu orang.            !\n");
    printf("===================================================================\n");
    printf("\n");

    printf("\n");
    printf("===================================================================\n");
    printf("--------------------------------LIBRA------------------------------\n");
    printf("!   Pengertian Umum:                                              !\n");
    printf("!   Simbolnya adalah timbangan, yang melambangkan keadilan,       !\n");
    printf("!   keseimbangan, dan harmoni. Libra adalah tanda udara yang      !\n");
    printf("!   mencerminkan kerjasama, kecantikan, dan diplomasi.            !\n");
    printf("!                                                                 !\n");
    printf("!   Tanggal      : 23 September - 22 Oktober.                     !\n");
    printf("!   Sifat        : Harmonis, sosial, romantis.                    !\n");
    printf("!   Kelebihan    : Diplomatis, adil.                              !\n");
    printf("!   Kekurangan   : Indecisive, tidak tegas.                       !\n");
    printf("!   Cocok dengan : Gemini, Aquarius.                              !\n");
    printf("!   Tambahan     : Senang kesenangan, memperhatikan keseimbangan. !\n");
    printf("===================================================================\n");
    printf("\n");

    printf("\n");
    printf("===================================================================\n");
    printf("-------------------------------SCORPIO-----------------------------\n");
    printf("!   Pengertian Umum:                                              !\n");
    printf("!   Scorpio adalah kalajengking, yang melambangkan intensitas,    !\n");
    printf("!   kekuatan, dan transformasi. Scorpio adalah tanda air yang     !\n");
    printf("!   menyoroti kecerdasan emosional, loyalitas, dan ketajaman.     !\n");
    printf("!                                                                 !\n");
    printf("!   Tanggal      : 23 Oktober - 21 November.                      !\n");
    printf("!   Sifat        : Intens, penuh misteri, posesif.                !\n");
    printf("!   Kelebihan    : Ketajaman, penuh semangat.                     !\n");
    printf("!   Kekurangan   : Penuh dendam, manipulatif.                     !\n");
    printf("!   Cocok dengan : Cancer, Pisces.                                !\n");
    printf("!   Tambahan     : Berhati-hati, suka mendalami.                  !\n");
    printf("===================================================================\n");
    printf("\n");

    printf("\n");
    printf("===================================================================\n");
    printf("-----------------------------SAGITTARIUS---------------------------\n");
    printf("!   Pengertian Umum:                                              !\n");
    printf("!   Sagittarius diwakili oleh seorang pemanah, yang melambangkan  !\n");
    printf("!   petualangan, optimisme, dan kebebasan. Sagittarius adalah     !\n");
    printf("!   tanda api yang mencerminkan kebebasan, pengetahuan, dan       !\n");
    printf("!   semangat petualangan.                                         !\n");
    printf("!                                                                 !\n");
    printf("!   Tanggal      : 22 November - 21 Desember.                     !\n");
    printf("!   Sifat        : Petualang, optimis, filosofis.                 !\n");
    printf("!   Kelebihan    : Berani, jujur.                                 !\n");
    printf("!   Kekurangan   : Tidak sabar, kurang konsisten.                 !\n");
    printf("!   Cocok dengan : Aries, Leo.                                    !\n");
    printf("!   Tambahan     : Suka belajar, independen.                      !\n");
    printf("===================================================================\n");
    printf("\n");

    printf("\n");
    printf("===================================================================\n");
    printf("------------------------------CAPRICORN----------------------------\n");
    printf("!   Pengertian Umum:                                              !\n");
    printf("!   Capricorn diwakili oleh kambing jantan, yang melambangkan     !\n");
    printf("!   ambisi, disiplin, dan tanggung jawab. Capricorn adalah tanda  !\n");
    printf("!   bumi yang menyoroti kesuksesan, keteguhan, dan konservatisme. !\n");
    printf("!                                                                 !\n");
    printf("!   Tanggal      : 22 Desember - 19 Januari.                      !\n");
    printf("!   Sifat        : Ambisius, praktis, konservatif.                !\n");
    printf("!   Kelebihan    : Bertanggung jawab, disiplin.                   !\n");
    printf("!   Kekurangan   : Dingin, terlalu serius.                        !\n");
    printf("!   Cocok dengan : Taurus, Virgo.                                 !\n");
    printf("!   Tambahan     : Fokus pada tujuan, suka tradisi.               !\n");
    printf("===================================================================\n");
    printf("\n");
}
